name: Code Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Prettier check
        run: npm run format:check
